select
    observation_id::varchar as observation_id,
    snapshot_id::varchar as snapshot_id,
    protocol::varchar as protocol,
    event_type::varchar as event_type,
    chain::varchar as chain,
    feed_address::varchar as feed_address,
    base_asset::varchar as base_asset,
    quote_asset::varchar as quote_asset,
    round_id::varchar as round_id,
    answer_raw::varchar as answer_raw,
    feed_decimals::number(38, 0) as feed_decimals,
    price::number(38, 18) as price,
    feed_updated_at::timestamp_tz as feed_updated_at,
    observed_at::timestamp_tz as observed_at,
    block_number::number(38, 0) as block_number,
    block_timestamp::timestamp_tz as block_timestamp,
    ingested_at::timestamp_tz as ingested_at,
    producer_version::varchar as producer_version,
    schema_version::varchar as schema_version,
    source_topic::varchar as source_topic,
    kafka_timestamp::timestamp_tz as kafka_timestamp,
    kafka_partition::number(38, 0) as kafka_partition,
    kafka_offset::number(38, 0) as kafka_offset,
    kafka_key::varchar as kafka_key,
    json_value::varchar as json_value,
    bronze_processed_at::timestamp_tz as bronze_processed_at,
    bronze_file::varchar as bronze_file,
    silver_processed_at::timestamp_tz as silver_processed_at,
    silver_job_version::varchar as silver_job_version,
    price_date::date as price_date,
    source_file::varchar as source_file,
    source_file_row_number::number(38, 0) as source_file_row_number,
    loaded_at::timestamp_tz as loaded_at
from {{ source('blockchain_raw', 'chainlink_prices') }}
