select
    event_id::varchar as event_id,
    protocol::varchar as protocol,
    chain::varchar as chain,
    event_type::varchar as event_type,
    event_date::date as event_date,
    block_timestamp::timestamp_tz as block_timestamp,
    transaction_hash::varchar as transaction_hash,
    block_number::number(38, 0) as block_number,
    log_index::number(38, 0) as log_index,
    kafka_timestamp::timestamp_tz as kafka_timestamp,
    ingested_at::timestamp_tz as ingested_at,
    producer_version::varchar as producer_version,
    schema_version::varchar as schema_version,
    bronze_processed_at::timestamp_tz as bronze_processed_at,
    bronze_file::varchar as bronze_file,
    contract_address::varchar as contract_address,
    raw_data::varchar as raw_data,
    raw_topics::variant as raw_topics,
    reserve::varchar as reserve,
    user::varchar as user,
    repayer::varchar as repayer,
    amount_raw::varchar as amount_raw,
    use_atokens::boolean as use_atokens,
    silver_processed_at::timestamp_tz as silver_processed_at,
    silver_job_version::varchar as silver_job_version,
    source_file::varchar as source_file,
    source_file_row_number::number(38, 0) as source_file_row_number,
    loaded_at::timestamp_tz as loaded_at
from {{ source('blockchain_raw', 'aave_repays') }}
