with lending_activities as (
    select
        borrows.event_id,
        'BORROW' as activity_type,
        borrows.block_timestamp,
        borrows.block_number,
        borrows.transaction_hash,
        borrows.log_index,
        borrows.reserve_token_key as token_key,
        borrows.amount_raw,
        borrows.borrow_amount as amount,
        borrows.price_usd,
        borrows.amount_usd,
        borrows.price_feed_updated_at,
        borrows.price_age_seconds,
        borrows.price_status,
        borrows.price_status_reason,
        borrows.mapped_feed_address,
        borrows.matched_observation_id,
        borrows.matched_feed_address,
        borrows.user,
        borrows.on_behalf_of,
        borrows.interest_rate_mode,
        borrows.borrow_rate_raw,
        borrows.referral_code,
        cast(null as varchar) as repayer,
        cast(null as boolean) as use_atokens
    from {{ ref('fact_aave_borrow_valued') }} as borrows

    union all

    select
        repays.event_id,
        'REPAY' as activity_type,
        repays.block_timestamp,
        repays.block_number,
        repays.transaction_hash,
        repays.log_index,
        repays.reserve_token_key as token_key,
        repays.amount_raw,
        repays.repay_amount as amount,
        repays.price_usd,
        repays.amount_usd,
        repays.price_feed_updated_at,
        repays.price_age_seconds,
        repays.price_status,
        repays.price_status_reason,
        repays.mapped_feed_address,
        repays.matched_observation_id,
        repays.matched_feed_address,
        repays.user,
        cast(null as varchar) as on_behalf_of,
        cast(null as number(38, 0)) as interest_rate_mode,
        cast(null as varchar) as borrow_rate_raw,
        cast(null as number(38, 0)) as referral_code,
        repays.repayer,
        repays.use_atokens
    from {{ ref('fact_aave_repay_valued') }} as repays
)

select
    activities.event_id,
    activities.activity_type,
    activities.block_timestamp,
    activities.block_number,
    activities.transaction_hash,
    activities.log_index,
    activities.token_key,
    tokens.token_address,
    tokens.symbol as token_symbol,
    tokens.name as token_name,
    tokens.decimals as token_decimals,
    activities.amount_raw,
    activities.amount,
    activities.price_usd,
    activities.amount_usd,
    activities.price_feed_updated_at,
    activities.price_age_seconds,
    activities.price_status,
    activities.price_status_reason,
    activities.mapped_feed_address,
    activities.matched_observation_id,
    activities.matched_feed_address,
    activities.price_status = 'priced' as has_valid_usd_valuation,
    activities.user,
    activities.on_behalf_of,
    activities.interest_rate_mode,
    activities.borrow_rate_raw,
    activities.referral_code,
    activities.repayer,
    activities.use_atokens
from lending_activities as activities
inner join {{ ref('dim_token') }} as tokens
    on activities.token_key = tokens.token_key
